In [2]:
"""
import json
import spacy

wordllist = ['goudatlog', 'frontend', 'titan', 'compare', 'front', 'index', 'validation', 'test', 'insights', 'business']
tokens = nlp(" ".join(str(s) for s in wordlist))
for token in tokens:
    wordVec = token.vector
"""
import numpy as np
a = np.array([[1,2,3],[3,2,1]])
print (a, a.shape)

[[1 2 3]
 [3 2 1]] (2, 3)


In [5]:
a = a.reshape(3,2)
print (a, a.shape)

[[1 2]
 [3 3]
 [2 1]] (3, 2)


In [6]:
a = a.reshape(3,2,1)
print (a, a.shape)

[[[1]
  [2]]

 [[3]
  [3]]

 [[2]
  [1]]] (3, 2, 1)


In [7]:
a = a.reshape(1,3,2,)
print (a, a.shape)

[[[1 2]
  [3 3]
  [2 1]]] (1, 3, 2)


In [8]:
b = np.array([4,5,6,6,5,4])
b = b.reshape(1,3,2)
c = np.empty((1,3,2))
print(b,c)

[[[4 5]
  [6 6]
  [5 4]]] [[[8.6e-322 0.0e+000]
  [0.0e+000 0.0e+000]
  [0.0e+000 0.0e+000]]]


In [9]:
print(a.size,b.size,c.size)

6 6 6


In [29]:
c = np.array([])
print (c,c.shape,c.size)

[] (0,) 0


In [12]:
if c:
    print (True)
else:
    print (False)

C:\Users\bmareddy\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  """Entry point for launching an IPython kernel.


False


In [32]:
a = a.reshape(1,3,2)
b = b.reshape(1,3,2)
if c.size == 0:
    c = a
else:
    c = np.concatenate([c,a],axis = 0)
print (c,c.shape,c.size)

[[[1 2]
  [3 3]
  [2 1]]

 [[4 5]
  [6 6]
  [5 4]]

 [[1 2]
  [3 3]
  [2 1]]] (3, 3, 2) 18


In [34]:
print (c[0])

[[1 2]
 [3 3]
 [2 1]]


In [35]:
print (c[(0,0,1)])

2


In [42]:
ma0 = c.mean(axis = 0)
ma1 = c.mean(axis = 1)
ma2 = c.mean(axis = 2)
print (ma0,ma0.shape,ma0.size)
print (ma1,ma1.shape,ma1.size)
print (ma2,ma2.shape,ma2.size)

[[2. 3.]
 [4. 4.]
 [3. 2.]] (3, 2) 6
[[2. 2.]
 [5. 5.]
 [2. 2.]] (3, 2) 6
[[1.5 3.  1.5]
 [4.5 6.  4.5]
 [1.5 3.  1.5]] (3, 3) 9


In [43]:
print (a, a.reshape(3,1,2))

[[[1 2]
  [3 3]
  [2 1]]] [[[1 2]]

 [[3 3]]

 [[2 1]]]


In [6]:
print(list(a.reshape(6,)))

[1, 2, 3, 3, 2, 1]


In [7]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [10]:
a.reshape(6,)

array([1, 2, 3, 3, 2, 1])

In [12]:
x = np.array([[0.58376017]])
print(x,x.shape,x.size)

[[0.58376017]] (1, 1) 1


In [15]:
print(float(x.reshape(1,)))

0.58376017
